"""Initial schema creation

Revision ID: 4d4c55197451
Revises: 
Create Date: 2026-06-29 15:41:17.499572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4c55197451'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shared_credentials', sa.JSON(), nullable=True),
    sa.Column('shared_user_agent', sa.Text(), nullable=True),
    sa.Column('shared_commands', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('ip_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_profiles',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('abuse_score', sa.Integer(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.String(length=50), nullable=True),
    sa.Column('org', sa.String(length=255), nullable=True),
    sa.Column('last_enriched', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('unique_ips', sa.Integer(), nullable=True),
    sa.Column('top_credentials', sa.JSON(), nullable=True),
    sa.Column('top_countries', sa.JSON(), nullable=True),
    sa.Column('detected_campaigns', sa.JSON(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('pdf_content', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sensor_type', sa.String(length=10), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=False),
    sa.Column('ssh_username', sa.String(length=255), nullable=True),
    sa.Column('ssh_password', sa.String(length=255), nullable=True),
    sa.Column('ssh_client_version', sa.String(length=255), nullable=True),
    sa.Column('ssh_commands', sa.JSON(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('http_path', sa.Text(), nullable=True),
    sa.Column('http_query', sa.Text(), nullable=True),
    sa.Column('http_headers', sa.JSON(), nullable=True),
    sa.Column('http_body', sa.Text(), nullable=True),
    sa.Column('http_user_agent', sa.Text(), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_campaign_id'), 'events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_events_sensor_type'), 'events', ['sensor_type'], unique=False)
    op.create_index(op.f('ix_events_source_ip'), 'events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('mitre_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=50), nullable=False),
    sa.Column('technique_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_tags_event_id'), 'mitre_tags', ['event_id'], unique=False)
    op.create_index(op.f('ix_mitre_tags_technique_id'), 'mitre_tags', ['technique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitre_tags_technique_id'), table_name='mitre_tags')
    op.drop_index(op.f('ix_mitre_tags_event_id'), table_name='mitre_tags')
    op.drop_table('mitre_tags')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_source_ip'), table_name='events')
    op.drop_index(op.f('ix_events_sensor_type'), table_name='events')
    op.drop_index(op.f('ix_events_campaign_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('reports')
    op.drop_table('ip_profiles')
    op.drop_table('credentials')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
