"""Add processed column to events

Revision ID: 6d3fed31f0a7
Revises: 4d4c55197451
Create Date: 2026-06-29 16:12:52.079734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3fed31f0a7'
down_revision: Union[str, Sequence[str], None] = '4d4c55197451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('processed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_events_processed'), 'events', ['processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_processed'), table_name='events')
    op.drop_column('events', 'processed')
    # ### end Alembic commands ###
